# spring.datasource.url=jdbc:mysql://ls-f7c53c1f43157d2809664bcbaadd8842af4f5151.cjwsmct3ucx3.ap-northeast-2.rds.amazonaws.com:3306/spring5
# spring.datasource.password=dong0305
# spring.datasource.username=dbmasteruser
spring:
    h2:
        console:
            enabled: true
            path: /console
            settings: 
                web-allow-others: true
    datasource:
        url: jdbc:h2:~/test;
        username: sa
        password:
        driverClassName: org.h2.Driver
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                show_sql: true
                format_sql: true

server:
    servlet:
        session:
            tracking-modes: cookie